# Generated by Django 5.1.7 on 2025-03-11 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='barberprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='barberprofile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='barberprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='barberprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='barberprofile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='barberprofile',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='barberprofile',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='name',
            field=models.CharField(blank=True, default='barber', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='photo',
            field=models.ImageField(blank=True, default='user-default.jpg', null=True, upload_to='media/barbers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='user-default.jpg', null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=None)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='app.barberprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='specialties',
            field=models.ManyToManyField(related_name='barbers', to='app.specialty'),
        ),
    ]
